name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  #- gpt-3.5-turbo-0125
  #- Meta-Llama-3.3-70B-Instruct
  #- Meta-Llama-3.1-405B-Instruct
  - gemma-3-27b-it
  - claude-3.7-sonnet
  - gemini-2.5-flash-preview
  - grok-3-beta
  - cohere-command-R7B
  - Qwen-Plus
  - Mistral-8B
  #- RWKV-v5-World-3B
  - Phi4